server:
  port: ":17758"

mysql:
  host: 172.17.81.21
  port: 3306
  user: root
  pass: Arcvideo@01
  database: amam
  param: charset=utf8mb4&parseTime=True&loc=Local
redis:
  network: tcp
  host: 172.17.81.21
  port: 6379
  pass: Arcvideo@01
  db: 13

log:
  level: info
  formatter: line
  showLine: true
  outFile: true
  logInConsole: true
  logDir: logs

transcoder:
  workDir: /usr/local/arcvideo/yx/transcoder
  xmlPath: /usr/local/arcvideo/yx/xml
  imageExeWorkDir: /usr/local/arcvideo/yx/transcoder
  imageExeName: imageBlend
